<?php

acf_add_local_field_group(array(
    'key' => 'group_57ed6cdb4658c',
    'title' => 'Big Banner',
    'fields' => array(
        array(
            'key' => 'field_57ed6cdfd35f6',
            'label' => 'Image',
            'name' => 'bigbanner__image',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'id',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_57ed6ce6d35f7',
            'label' => 'Title',
            'name' => 'bigbanner__title',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_57ed6cf4d35f9',
            'label' => 'Content',
            'name' => 'bigbanner__content',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array(
            'key' => 'field_57ed6cecd35f8',
            'label' => 'Subtext',
            'name' => 'bigbanner__subtext',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '70',
            ),
        ),
    array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '77',
            ),
        ),
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '113',
            ),
        ),
        /*array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '95',
            ),
        ),*/
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '116',
            ),
        ),
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '116',
            ),
        ),
        array(
            array(
                'param' => 'page',
                'operator' => '==',
                'value' => '101',
            ),
        ),
    ),

    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
